services:
  ### PgAdmin #########################################
  pgadmin:
    container_name: "${APP_NAME}-pgadmin"
    hostname: pgadmin
    networks:
      backend:
        aliases:
          - pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    depends_on:
      - postgres
#    ports:
#      - "5050:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
