services:
  ### Postgres #########################################
  postgres-kc:
    container_name: "${APP_NAME}-postgres-kc"
    hostname: postgres-kc
    networks:
      backend:
        aliases:
          - postgres-kc
    image: postgres:13.1
    restart: unless-stopped
    mem_limit: 5120m
    security_opt:
      - seccomp:unconfined
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      POSTGRES_DB: keycloak
#    ports:
#      - "5433:5432"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/var/lib/postgresql/data
