volumes:
  website: ~
  # vendor: ~
  # node_modules: ~

services:
  ### NoMercy.tv ########################################
  website:
    container_name: "${APP_NAME}-website"
    hostname: website
    networks:
      backend:
        aliases:
          - website
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/var/www/html/
      # - ./data/storage/logs:/var/www/html/storage/logs
      # - vendor:/var/www/html/vendor/
      # - node_modules:/var/www/html/node_modules/
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # ports:
    #     - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
